<?php

function tbr_salaries_views_api() {
   return array(
      'api' => 3,
   );
}

function tbr_salaries_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-tbr-salary-data-page" or $form['#id'] == "views-exposed-form-tbr-salary-data-history-page") {
    
    $form['institution']['#type'] = "select";
    $form['institution']['#size'] = null;
    $form['institution']['#options'] = array();
	$form['institution']['#options'][''] = '';
	
	$results = null;
	$cache_key = "salaries_institutions";
	$cache = cache_get($cache_key);
	
	if ($cache) {
		//drupal_set_message("Content Type List Loaded from Cache: " . date("Y-m-d H:i:s", $cache->created));
		$results = $cache->data;
	}
	else {
	   //Set the database to the salaries database
	   db_set_active('tbr_data_salaries');
	   
	   //Get distinct years
	   $result = db_query('SELECT DISTINCT(institution) FROM salaries ORDER BY institution ASC');
       $results = $result->fetchAll(); 
	   cache_set($cache_key, $results, 'cache', CACHE_TEMPORARY);
	   //drupal_set_message("Content Type List Saved to Cache");

	   //Set the database back to the default drupal database
	   db_set_active();
   }
   
   foreach ($results as $record) {
	   //Add the years to the select list array
	   $form['institution']['#options'][$record->institution] = $record->institution;
   }
  }
  
  
  if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-tbr-salary-data-history-page") {

	$form['year']['#type'] = "select";
	$form['year']['#size'] = null;
	$form['year']['#options'] = array();
	$form['year']['#options'][""] = ""; 
	
	$results = null;
	$cache_key = "salaries_years";
	$cache = cache_get($cache_key);
	if ($cache) {
		drupal_set_message("Content Type List Loaded from Cache: " . date("Y-m-d H:i:s", $cache->created));
		$results = $cache->data;
	}
	else {
	   //Set the database to the salaries database
	   db_set_active('tbr_data_salaries');
	   
	   //Get distinct years
	   $result = db_query('SELECT DISTINCT(year) FROM salaries ORDER BY year DESC');
       $results = $result->fetchAll(); 
	   cache_set($cache_key, $results, 'cache', CACHE_TEMPORARY);
	   //drupal_set_message("Content Type List Saved to Cache");

	   //Set the database back to the default drupal database
	   db_set_active();
   }
   
   foreach ($results as $record) {
	   //Add the years to the select list array
	   $form['year']['#options'][$record->year] = $record->year;
   }
 
  }
  

}


